# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Life goes on
email: 2k@dangkhoi.info
description: i write the thought on my mind, whatever you like this or not, who's care?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dangkhoi.info" # the base hostname & protocol for your site
twitter_username: koi_2k
github_username:  koi-2k

# Build settings
markdown: kramdown
